[package]
name = "pendulum"
version = "0.1.0"
authors = ["Jonathan Abramson <zenpoy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15"